[package]
name = "suffix_array"
version = "0.1.0"
authors = ["hucsmn <hucsmn@hotmail.com>"]
edition = "2018"

[dev-dependencies]
rand = "0.6"
criterion = "0.2"

[[bench]]
name = "construct"
harness = false
