[package]
name = "suffix_array"
version = "0.2.0"
authors = ["hucsmn <hucsmn@hotmail.com>"]
edition = "2018"
homepage = "https://github.com/hucsmn/suffix_array"
repository = "https://github.com/hucsmn/suffix_array"
license = "MIT"
readme = "README.md"
categories = ["algorithms"]
keywords = ["suffix_array", "binary", "sais"]
maintenance = { status = "passively-maintained" }
description = """
Suffix array construction and searching algorithms for in-memory binary
data, focusing on space efficiency.
"""

[dev-dependencies]
rand = "*"
criterion = "0.2"
proptest = "0.9"

[[bench]]
name = "construct"
harness = false

[[bench]]
name = "contains"
harness = false

[[bench]]
name = "search_all"
harness = false

[[bench]]
name = "search_prefix"
harness = false
